version: '3'

services:
  db:
    image: mysql/mysql-server:8.0
    container_name: mysql1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gestionscolaire
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306

  app:
    image: app:latest
    ports:
       - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql1:3306/gestionscolaire?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root 
    depends_on:
       - db
